fix loggit tool

diff --git a/dev-util/joetoolkit/files/joetoolkit/loggit b/dev-util/joetoolkit/files/joetoolkit/loggit
--- a/dev-util/joetoolkit/files/joetoolkit/loggit
+++ b/dev-util/joetoolkit/files/joetoolkit/loggit
@@ -2,18 +2,13 @@
 # /root/bin/loggit
 # Joe Brendler 1 Mar 2009
 #
-# Borrowed from John Brendler's Rev. 20 July 2007
+# Modified from John Brendler's Rev. 20 July 2007
 
-# Standard code snippet to include at the bottom of cron scripts.
-# The $? variable expands to the exit status of the previous command.
-# To include, use ". /root/bin/loggit" or "source /root/bin/loggit
-
-EXIT_STATUS=$?
-
+[[ $# -gt 2 ]] && E_message "invalid loggit arguments" && exit 1;
+[[ -z $2 ]] && EXIT_STATUS=0 || EXIT_STATUS="$2";
+[[ -z $1 ]] && PROGRAM=Unspecified || PROGRAM="$1";
 case $EXIT_STATUS in
-        0) PRIORITY="notice" && MESSAGE="succeeded.";;
-        *) PRIORITY="err" && MESSAGE="failed with exit status ${EXIT_STATUS}";;
-esac
-
-/usr/bin/logger -p cron.$PRIORITY "$0 $MESSAGE"
-
+    0) PRIORITY="notice" && MESSAGE="succeeded." ;;
+    *) PRIORITY="err" && MESSAGE="failed with exit status ${EXIT_STATUS}" ;;
+esac;
+/usr/bin/logger -p cron.$PRIORITY "$PROGRAM $MESSAGE"
