kernelupdate-0.8.1.ebuild - accomodate 0.0.0 tarball and ebuild

diff --git a/sys-kernel/kernelupdate/files/kernelupdate b/sys-kernel/kernelupdate/files/kernelupdate
--- a/sys-kernel/kernelupdate/files/kernelupdate
+++ b/sys-kernel/kernelupdate/files/kernelupdate
@@ -346,47 +346,70 @@ make_tarball()
 }
 
 publish_tarball() {
+    # publish_tarball must also publish the tarball corresponding to the template ebuild
+    # or publish_ebuild will fail because pkgdev wont be able to create a manifest
+    publish_tarball_command_sequence=()
+    publish_tarball_command_sequence+=("#!/bin/bash" \
+        'export SSH_AUTH_SOCK="'"${SSH_AUTH_SOCK}"'"' \
+        "ssh-add -l 2>/dev/null >/dev/null" \
+        '[ $? -ge 2 ] && ssh-agent -a ${SSH_AUTH_SOCK} >/dev/null' \
+        "echo 'ssh-agent added, listing keys ...'" \
+        "ssh-add -l" \
+        "source ${my_devel_dir_credentials}" \
+        "echo" \
+        "cd ${devel_dir%/}/" \
+        "echo new PWD: \${PWD}" \
+        "git pull" )
+
+    # if the version 0.0.0 tarball for this package does not exist, create it and upload to github repo
+    if [ ! -e ${devel_dir%/}/${kernel_basename}-0.0.0.tar.bz2 ] ; then
+        # use the README-instructions file in /etc/kernelupdate as content for the dummy tarball 0.0.0
+        message "creating dummy tarball ${devel_dir%/}/${kernel_basename}-0.0.0.tar.bz2 ..."
+        tar -cvjpf ${devel_dir%/}/${kernel_basename}-0.0.0.tar.bz2 /etc/kernelupdate/README-instructions
+        message_n "changing ownership for upload ..."
+        chown -R ${user}:${user} ${devel_dir%/}/ ; right_status $?
+        publish_tarball_command_sequence+=("git add ${kernel_basename}-0.0.0.tar.bz2")
+    else
+        d_message "tarball ${devel_dir%/}/${kernel_basename}-0.0.0.tar.bz2 already exists. Not creating." 3
+    fi
+
+    # copy the new tarball to devel_dir and upload to github repo
     echo; message "copying package ${distrib_dir%/}/${kernel_image_name}.tar.bz2 to ${devel_dir%/}/"
     cp -v ${distrib_dir%/}/${kernel_image_name}.tar.bz2 ${devel_dir%/}/
-    message "changing ownership for upload"
-    chown ${user}:${user} ${devel_dir%/}/${kernel_image_name}.tar.bz2
+    message_n "changing ownership for upload ..."
+    chown -R ${user}:${user} ${devel_dir%/}/ ; right_status $?
 
-    cd ${old_dir} && message "Now working in $PWD"
+    publish_tarball_command_sequence+=( \
+        "git status" \
+        "git add ${kernel_image_name}.tar.bz2" \
+        "git commit -m \"adding ${kernel_image_name}\"" \
+        'eval "git push git@github.com:${gituser}/${gitrepo}.git master"' \
+        'git push' \
+        '' )
+
+    # move to the devel_dir, so git commands are relative to it locally
+    old_dir=$(pwd)
+    message "leaving $(pwd)" &&  cd ${devel_dir} && message "Now working in $(pwd)"
 
     echo; message "Building publish_tarball_cmd_file [ ${publish_tarball_cmd_file} ]..."
+    # actually build the publish_tarball_cmd_file from the publish_tarball_command_sequence
     # first command uses single ">", to initialize the file; then others use ">>"
-    echo "#!/bin/bash" > ${publish_tarball_cmd_file}
-    # set SSH_AUTH_SOCK env var to a fixed value
-    echo 'export SSH_AUTH_SOCK="'"${SSH_AUTH_SOCK}"'"' >> ${publish_tarball_cmd_file}
-    # test whether ${SSH_AUTH_SOCK} is valid
-    echo "ssh-add -l 2>/dev/null >/dev/null" >> ${publish_tarball_cmd_file}
-    # if not valid, then start ssh-agent using ${SSH_AUTH_SOCK}
-    echo '[ $? -ge 2 ] && ssh-agent -a ${SSH_AUTH_SOCK} >/dev/null' >> ${publish_tarball_cmd_file}
-    echo "echo 'ssh-agent added, listing keys ...'" >> ${publish_tarball_cmd_file}
-    # list ssh keys. Note: this method depends on users .bashrc to have loaded them, if not, then do it here
-    echo "ssh-add -l" >> ${publish_tarball_cmd_file}
-    # source github credentials to format the git push command and identify keys to load
-    echo "source ${my_devel_dir_credentials}" >> ${publish_tarball_cmd_file}
-    # check for ssh keys, and add if they are not already loaded
-    [[ -z $(ssh-add -l | grep -v "no identities") ]] && ssh-add ${gitsshkey}
-    # now do git pull, push, push using ssh key
-    echo "echo" >> ${publish_tarball_cmd_file}
-    echo "cd ${devel_dir%/}/" >> ${publish_tarball_cmd_file}
-    echo "echo new PWD: \${PWD}" >> ${publish_tarball_cmd_file}
-    echo "git pull" >> ${publish_tarball_cmd_file}
-    echo "git status" >> ${publish_tarball_cmd_file}
-    echo "git add ${kernel_image_name}.tar.bz2" >> ${publish_tarball_cmd_file}
-    echo "git commit -m \"adding ${kernel_image_name}\"" >> ${publish_tarball_cmd_file}
-    echo 'eval "git push git@github.com:${gituser}/${gitrepo}.git master"'  >> ${publish_tarball_cmd_file}
-    echo 'git push' >> ${publish_tarball_cmd_file}
-    echo  >> ${publish_tarball_cmd_file}
+    echo ${publish_tarball_command_sequence[0]} > ${publish_tarball_cmd_file}
+    for ((i=1; i<${#publish_tarball_command_sequence[@]}; i++))
+    do
+        message_n "adding line $i: [ "
+        echo -n ${publish_tarball_command_sequence[$i]}
+        echo -n " ] ..."
+        echo ${publish_tarball_command_sequence[$i]} >> ${publish_tarball_cmd_file}
+        right_status $?
+    done
 
-    cd ${old_dir} && message "Now working in $PWD"
+    message "leaving $(pwd)" &&  cd ${old_dir} && message "Now working in $(pwd)"
     separator "contents of ${publish_tarball_cmd_file}... " $(hostname)
     cat ${publish_tarball_cmd_file}
-    separator "setting permissions on ${publish_tarball_cmd_file}... " $(hostname)
-    chown joe:joe ${publish_tarball_cmd_file}
-    chmod +x ${publish_tarball_cmd_file}
+    message_n "setting permissions on ${publish_tarball_cmd_file}... "
+    chown joe:joe ${publish_tarball_cmd_file} && \
+    chmod +x ${publish_tarball_cmd_file} ; right_status $?
 
     # now actually execute the publication by running the publication command file
     separator "now executing commands in ${publish_tarball_cmd_file}... " $(hostname)
@@ -398,8 +421,8 @@ publish_ebuild() {
     #   (but then you have to build all 12 kernels before anyone can use the ebuild)
     #   (so I'm going back to an ebuild for the kernel for each model)
 
-    ebuild_command_sequence=()
-    ebuild_command_sequence=('#!/bin/bash' \
+    publish_ebuild_command_sequence=()
+    publish_ebuild_command_sequence=('#!/bin/bash' \
         'export SSH_AUTH_SOCK="'"${SSH_AUTH_SOCK}"'"' \
         "ssh-add -l 2>/dev/null >/dev/null" \
         '[ $? -ge 2 ] && ssh-agent -a ${SSH_AUTH_SOCK} >/dev/null' \
@@ -415,7 +438,7 @@ publish_ebuild() {
     if [[ ! -d "${ebuild_dir}" ]] ; then
       mkdir -pv -m 755 "${ebuild_dir}"
       chown -R ${user}:${user} "${ebuild_dir}"
-      ebuild_command_sequence+=("git add ./")
+      publish_ebuild_command_sequence+=("git add ./")
     else
       d_message "${ebuild_dir} already exists; not creating." 3
     fi
@@ -430,7 +453,7 @@ publish_ebuild() {
         cp  ${CONF_DIR%/}/template_linux-MODEL_joetoo_kernelimage-0.0.0.ebuild \
            ${ebuild_dir%/}/linux-${model}_joetoo_kernelimage-0.0.0.ebuild
         chown -R ${user}:${user} "${ebuild_dir%/}/"
-        ebuild_command_sequence+=("git add linux-${model}_joetoo_kernelimage-0.0.0.ebuild")
+        publish_ebuild_command_sequence+=("git add linux-${model}_joetoo_kernelimage-0.0.0.ebuild")
       else
 	E_message "${BRon}Error: ${Boff} ${CONF_DIR%/}/template_linux-MODEL_joetoo_kernelimage-0.0.0.ebuild does not exist" 3
       fi
@@ -446,7 +469,7 @@ publish_ebuild() {
         cp  ${CONF_DIR%/}/template_linux-MODEL_joetoo_kernelimage-0.0.0.metadata.xml \
            ${ebuild_dir%/}/metadata.xml
         chown -R ${user}:${user} "${ebuild_dir%/}/"
-        ebuild_command_sequence+=("git add /metadata.xml")
+        publish_ebuild_command_sequence+=("git add /metadata.xml")
       else
 	E_message "${BRon}Error: ${Boff} ${CONF_DIR%/}/template_linux-MODEL_joetoo_kernelimage-0.0.0.metadata.xml does not exist" 3
       fi
@@ -489,7 +512,7 @@ publish_ebuild() {
     # remove the old Manifest file
     rm ${ebuild_dir%/}/Manifest 2>/dev/null
 
-    ebuild_command_sequence+=( \
+    publish_ebuild_command_sequence+=( \
         "pkgdev manifest -f -d ${DISTDIR}" \
         "git status" \
         "git add Manifest" \
@@ -500,13 +523,15 @@ publish_ebuild() {
         'git push' \
         '' )
 
-    echo ${ebuild_command_sequence[0]} > ${publish_ebuild_cmd_file}
-    for ((i=1; i<${#ebuild_command_sequence[@]}; i++))
+    # actually build the publish_ebuild_cmd_file from the publish_ebuild_command_sequence
+    # first command uses single ">", to initialize the file; then others use ">>"
+    echo ${publish_ebuild_command_sequence[0]} > ${publish_ebuild_cmd_file}
+    for ((i=1; i<${#publish_ebuild_command_sequence[@]}; i++))
     do
         message_n "adding line $i: [ "
-        echo -n ${ebuild_command_sequence[$i]}
+        echo -n ${publish_ebuild_command_sequence[$i]}
         echo -n " ] ..."
-        echo ${ebuild_command_sequence[$i]} >> ${publish_ebuild_cmd_file}
+        echo ${publish_ebuild_command_sequence[$i]} >> ${publish_ebuild_cmd_file}
         right_status $?
     done
 
@@ -517,15 +542,13 @@ publish_ebuild() {
     separator "contents of ${publish_ebuild_cmd_file}... " $(hostname)
     cat ${publish_ebuild_cmd_file}
     echo
-    message_n "setting permissions on ${publish_ebuild_cmd_file}... " $(hostname)
+    message_n "setting permissions on ${publish_ebuild_cmd_file}... "
     chown joe:joe ${publish_ebuild_cmd_file} && \
     chmod +x ${publish_ebuild_cmd_file} ; right_status $?
 
     # now actually execute the publication by running the publication command file
     separator "now executing commands in ${publish_ebuild_cmd_file}... " $(hostname)
     sudo -u ${user} ${publish_ebuild_cmd_file}
-
-
 }
 
 usage() {
@@ -593,7 +616,7 @@ display_vars ${#myvar} "${myvar}"
 
 make_sources_message() {
 # pull text from /etc/kernelupdate/README-instructions
-# ignore lines beginning with two #s (i.e. "##"
+# ignore lines beginning with two #s (i.e. "##")
 # echo lines beginning with one "#" in light blue
 # ehco other lines in bright white
 #
