add display_vars to script_header

diff --git a/dev-util/script_header_brendlefly/files/script_header_brendlefly b/dev-util/script_header_brendlefly/files/script_header_brendlefly
--- a/dev-util/script_header_brendlefly/files/script_header_brendlefly
+++ b/dev-util/script_header_brendlefly/files/script_header_brendlefly
@@ -160,7 +160,7 @@ CPR()  # Report the current position (row, col) of the cursor [tip: hit return a
 isnumber()      # test if $1 is a decimal number; return true/false
 { re='^[0-9]+$'; if echo "$1" | egrep -q "$re"; then return $TRUE; else return $FALSE; fi ; }
 
-ishex()      # test if $1 is a hexadecimal number; return true/false
+ishex()         # test if $1 is a hexadecimal number; return true/false
 { re='^[0-9a-fA-F]+$'; if echo "$1" | egrep -q "$re"; then return $TRUE; else return $FALSE; fi ; }
 
 checkroot()     # Run as root, of course.
@@ -227,7 +227,7 @@ while ! expr "${answer:0:1}" : [yYnN] >/dev/null;  # answer not a regex match
 do RCP; echo -en "$(repeat ' ' $(termwidth))";  ## blank the line
 RCP; message_n "$ps [Y/n]: " && read answer; done; }
 
-old_prompt()        # set external variable $answer based on reponse to prompt $1
+old_prompt()    # set external variable $answer based on reponse to prompt $1
 { ps=$1; SCP; echo -en "$ps [Y/n]: "   ### Not using '=~' because it's not in busybox
   while read answer && ! expr "${answer:0:1}" : [yYnN] >/dev/null;  # answer not a regex match
     do case ${answer:0:1} in [yY1]|"$TRUE") answer="n";; [nN0]|"$FALSE") answer="x";; esac
@@ -303,7 +303,64 @@ separator()     # draw a horizontal line with a simple title (arg $1) and prefac
   echo -n $(repeat "-" $(( $(termwidth) - $(( $msg_len + ${#Boff} )) )) ) && echo -e ${Boff} && \
   return 0 || return 1 ; }
 
-right_status()  # output 8 char [ ok/fail ] status at the right margin
+get_longest()    # return via echo to stdout the length of longest string in input $@
+{ ans=0; for x in $@; do [ ${#x} -gt $ans ] && ans=${#x}; done ; echo $ans ; }
+
+display_vars() # output dot-padded standard config display for each var in $@; incl bool_ lv_ ; $1=longest
+{
+  if ! isnumber $1 ; then E_message "Error: arg \$1 must be numeric longest expected input var name"; exit; fi
+  if [ $# -le 1 ] ; then E_message "Error: \$# not gt 1; arg 1 must be followed by var names"; exit; fi
+  maxlen=$(($1 + 2)); shift; for var_name in $@;
+  do
+    type="$(echo $var_name | awk  -F \_ '{print $1}')"
+    case ${type} in
+      "bool" )  # boolean convention: parameter is "bool_${var}" where ${var} is e.g. "VRBOSE"
+        var="$(echo $var_name | awk  -F \_ '{print $2}')"
+        eval "key=\$${var}"
+        pad="$(repeat '.' $(( ${maxlen} - ${#var})) )"
+        message "${LBon}${var}${pad}: [ $(status_color ${key})$(TrueFalse ${key}) ${LBon}]${Boff}"
+      ;;
+      "lv"   )  # lonstring convention: parameter is "lv_${var}" wehre ${var} is e.g. "CMDLINE"
+        var="$(echo $var_name | awk  -F \_ '{print $2}')"
+        eval "key=\$${var}"
+        pad="$(repeat '.' $(( ${maxlen} - ${#var})) )"
+        message_n "${LBon}${var}${pad}: [ ${Boff}"
+        echo_n_long ${maxlen} ${key}; echo -e " ${LBon}]${Boff}"
+      ;;
+      "BREAK"   )  # lonstring convention
+        echo
+      ;;
+      *      )  # all other variable types
+        var="${type}"
+        eval "key=\$${var}"
+        pad="$(repeat '.' $(( ${maxlen} - ${#var})) )"
+        message "${LBon}${var}${pad}: [ ${Boff}${key} ${LBon}]${Boff}"
+      ;;
+    esac
+  done
+}
+
+echo_n_long()    #  spread a long string over several lines, if needed.  $1=start
+{
+  if ! isnumber $1 ; then E_message "Error: arg \$1 must be numeric starting caracter position"; exit; fi
+  if [ $# -le 1 ] ; then E_message "Error: \$# not gt 1; arg 1 must be followed by a long string of input"; exit; fi
+  left=" * "; right=": [ "
+  start=$(( $1 + ${#left} + ${#right} )); shift; input="$@"; tw=$(termwidth); newline=""
+  for x in $input
+  do
+    d_echo "start: $start  #newline: ${#newline}   #x: ${#x}  tw: $tw   sum: $(( ${start} + ${#newline} + ${#x} + 1))" 5
+    if [[  $(( ${start} + ${#newline} + ${#x} + 1)) -le ${tw} ]] ; then
+      [[ ${#newline} -eq 0 ]] && newline="${x}" || newline="${newline} ${x}"
+    else
+      echo "${newline}"
+      start=0   # since next will be a new line
+      newline="${x}"
+    fi
+  done
+  echo -n "${newline}"
+}
+
+right_status()   # output 8 char [ ok/fail ] status at the right margin
 { # test message_n "good_test" ; right_status $?
   #      E_message_n "fail_test" && cat unexistent 2>/dev/null; right_status $?
   local msg status=$1
@@ -311,14 +368,14 @@ right_status()  # output 8 char [ ok/fail ] status at the right margin
   # go to start of line, *then* move fwd to 7 chars from the right margin ("[ xx ]" is 6)
   echo -en "\r" && CUF $(( $(termwidth) - 7 )) && echo -e "$msg" && return 0 || return 1 ; }
 
-d_right_status()  # output 8 char [ ok/fail ] status at the right margin, if $VERBOSE
+d_right_status() # output 8 char [ ok/fail ] status at the right margin, if $VERBOSE
 { # test with v=((verbosity+1)) and v=(($verbosity-1))
   # d_message_n "good_test" $v; d_right_status $? $v
   #      dE_message_n "fail_test" $v && cat unexistent 2>/dev/null; d_right_status $? $v
   local status=$1
   [[ $VERBOSE && $2 -le $verbosity ]] && right_status $status && return 0 || return 1 ; }
 
-sh_countdown()  # count-down seconds (arg $1)
+sh_countdown()   # count-down seconds (arg $1)
 { # special note: bb sh cannot use base#number notation with prefix 10# to ensure interpretation as base 10
   if [[ ! -z $1 ]]
   then rem_time="${1}" ;
@@ -340,7 +397,7 @@ sh_countdown()  # count-down seconds (arg $1)
   return 0
 }
 
-progress()      # display an arrow depicting progress (visualize $1 of $2 steps complete)
+progress()       # display an arrow depicting progress (visualize $1 of $2 steps complete)
 {
   [ $# -ne 2 ] && E_message "${BRon}Error - two arguments required (${BYon}step ${BRon}and ${BYon}number_of_steps${BRon})${Boff}"
   step=$1; number_of_steps=$2
@@ -366,10 +423,10 @@ progress()      # display an arrow depicting progress (visualize $1 of $2 steps 
   CUP $myrow $middlestart; echo -en "( ${pct_color}$percent%${Boff} )"; RCP
 }
 
-fe()            # find ebuild files matching filter "*$1*"
-{ echo "looking for ebuild(s) matching filter: $1"; find / -iname "*$1*.ebuild" -type f -print; }
+fe()             # find ebuild files matching filter "*$1*"
+{ echo "looking for ebuild(s) matching filter: $1"; find / -iname "*$1*.ebuild" -type f -print 2>/dev/null; }
 
-summarize_me()  # list contents of this script header (employ me with "source" or ".")
+summarize_me()   # list contents of this script header (employ me with "source" or ".")
 {
   echo
   separator "script_header_brendlefly-$BUILD | content summary" && \
